language: ruby
sudo: false
rvm:
  - 2.3.1
  - 2.3.3

before_install: gem install bundler -v 1.14.6

script: bin/travis

matrix:
  fast_finish: true

env:
  matrix:
    - BUILD_TYPE=rspec
    - BUILD_TYPE=rubocop
